requires 'perl', '5.16.0';
requires 'Kossy';
requires 'CPAN::Perl::Releases';
requires 'HTTP::Tiny';
requires 'IO::Socket::SSL';
requires 'Cache::Memcached::Fast::Safe';
requires 'Proclet';
requires 'Plack';
requires 'Plack::Builder::Conditionals';
requires 'Starlet';
requires 'List::Util';
requires 'Getopt::Long';
requires 'Test::Test';
